package main

func CreateTable() {
	db.Exec("CREATE TABLE `article` ( `id` int(11) NOT NULL AUTO_INCREMENT, `timec` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `timelastedit` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `needlogin` tinyint(1) DEFAULT '1', `namespace` varchar(128) NOT NULL DEFAULT 'main', `title` varchar(128) NOT NULL DEFAULT 'NO TITLE', `text` longtext, `tags` text, `viewcounter` int(11) DEFAULT NULL, `editcounter` int(11) DEFAULT NULL, PRIMARY KEY (`id`), FULLTEXT KEY `Search` (`namespace`,`title`,`tags`,`text`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1")

	db.Exec("CREATE TABLE `items` ( `ItemID` int(11) NOT NULL AUTO_INCREMENT, `timecreate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `timelastedit` timestamp NULL DEFAULT NULL, `needlogin` tinyint(1) DEFAULT '1', `APP` varchar(20) DEFAULT NULL, `viewcounter` int(11) DEFAULT NULL, `editcounter` int(11) DEFAULT NULL, `title1` varchar(128) DEFAULT NULL, `title2` varchar(128) NOT NULL, `text1` text, `text2` text, `tags1` varchar(256) DEFAULT NULL, `num1` int(64) DEFAULT NULL, `num2` int(64) DEFAULT NULL, `num3` int(64) DEFAULT NULL, PRIMARY KEY (`ItemID`), KEY `ItemID` (`ItemID`), KEY `num1` (`num1`), KEY `Search` (`ItemID`,`APP`,`title1`,`title2`,`num1`,`num2`,`num3`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1")

	db.Exec("CREATE TABLE `eventlog` ( `id` int(11) NOT NULL AUTO_INCREMENT, `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `name` varchar(256) DEFAULT NULL, `changeAPP` varchar(128) DEFAULT NULL, `changeID` int(11) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1")

	db.Exec("CREATE TABLE `BUarticle` ( `BUID` int(11) NOT NULL AUTO_INCREMENT, `BUtimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `id` int(11) NOT NULL, `timec` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `timelastedit` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `needlogin` tinyint(1) DEFAULT '1', `namespace` varchar(128) NOT NULL DEFAULT 'main', `title` varchar(128) NOT NULL DEFAULT 'NO TITLE', `text` longtext, `tags` text, `viewcounter` int(11) DEFAULT NULL, `editcounter` int(11) DEFAULT NULL, PRIMARY KEY (`BUID`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1")

	db.Exec("CREATE TABLE `BUitems` ( `BUItemID` int(11) NOT NULL AUTO_INCREMENT, `ItemID` int(11) DEFAULT NULL, `timecreate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `timelastedit` timestamp NULL DEFAULT NULL, `needlogin` tinyint(1) DEFAULT '1', `APP` varchar(20) DEFAULT NULL, `viewcounter` int(11) DEFAULT NULL, `editcounter` int(11) DEFAULT NULL, `title1` varchar(128) DEFAULT NULL, `title2` varchar(128) NOT NULL, `text1` text, `text2` text, `tags1` varchar(256) DEFAULT NULL, `num1` int(64) DEFAULT NULL, `num2` int(64) DEFAULT NULL, `num3` int(64) DEFAULT NULL, PRIMARY KEY (`BUItemID`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1")
}
